FROM maven:3-openjdk-17 as build
WORKDIR /app
COPY pom.xml pom.xml
COPY src/ src/
RUN mvn clean test
RUN mvn package


FROM openjdk:17
WORKDIR /app
COPY --from=build /app/target/account-management-0.0.1-SNAPSHOT.jar app.jar
EXPOSE 8080
CMD ["java", "-jar", "app.jar"]

