spring:
  mail:
    host: localhost
    port: 1025
  thymeleaf:
    mode: HTML
    cache: false
  datasource:
    url: 'jdbc:h2:mem:account-management'
    username: sa
    password: sa
  jpa:
    hibernate:
      ddl-auto: 'create-drop'
    show-sql: true

  messages:
    basename: i18n/messages
    cache-duration: PT1S
    encoding: UTF-8
app:
  cors:
    # Allow Ionic for JHipster by default (* no longer allowed in Spring Boot 2.4+)
    allowed-origins: 'http://localhost:8100,https://localhost:8100,http://localhost:9000,https://localhost:9000'
    # Enable CORS when running in GitHub Codespaces
    allowed-origin-patterns: 'https://*.githubpreview.dev'
    allowed-methods: '*'
    allowed-headers: '*'
    exposed-headers: 'Authorization,Link,X-Total-Count,X-${jhipster.clientApp.name}-alert,X-${jhipster.clientApp.name}-error,X-${jhipster.clientApp.name}-params'
    allow-credentials: true
    max-age: 1800
  security:
    authentication:
      jwt:
        # This token must be encoded using Base64 and be at least 256 bits long (you can type `openssl rand -base64 64` on your command line to generate a 512 bits one)
        base64-secret: OWZhNDE5NDMzOWQ0MzdhMDRhZjc5NjMxMDM2MWY1ZjExNWVjNmRkM2MzZjBlY2RkYmY0ODFlOGMwYzczYzRhODFhMDU4OTUyYzQ0OGM3NDFlZjJhMzQ5MDg2ZjI4NjQ4MTdkNGNlNjliMzcwODFlNjEyMWMxY2FkODk4YTU0ODc=
        # Token is valid 24 hours
        token-validity-in-seconds: 86400
        token-validity-in-seconds-for-remember-me: 2592000
  mail: # specific JHipster mail property, for standard properties see MailProperties
    base-url: http://127.0.0.1:8080
