spring:
  mail:
    host: localhost
    port: 1025
  thymeleaf:
    mode: HTML
  datasource:
    url: 'jdbc:h2:mem:account-management'
    username: sa
    password: sa
  jpa:
    hibernate:
      ddl-auto: 'create-drop'
    show-sql: true


