spring:
  mail:
    host: localhost
    port: 1025
  thymeleaf:
    mode: HTML
    cache: false
  datasource:
    url: 'jdbc:h2:mem:account-management'
    username: sa
    password: sa
  jpa:
    hibernate:
      ddl-auto: 'create-drop'
    show-sql: true

  messages:
    basename: i18n/messages
    cache-duration: PT1S
    encoding: UTF-8
